---
repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 1.1.0
    hooks:
      - id: sync_with_poetry

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.10
    hooks:
      - id: ruff
        args:
          - --fix

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
